// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wundernode_config.proto

package wgpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LogLevel int32

const (
	LogLevel_DEBUG   LogLevel = 0
	LogLevel_INFO    LogLevel = 1
	LogLevel_ERROR   LogLevel = 2
	LogLevel_WARNING LogLevel = 3
	LogLevel_PANIC   LogLevel = 4
	LogLevel_FATAL   LogLevel = 5
)

var LogLevel_name = map[int32]string{
	0: "DEBUG",
	1: "INFO",
	2: "ERROR",
	3: "WARNING",
	4: "PANIC",
	5: "FATAL",
}

var LogLevel_value = map[string]int32{
	"DEBUG":   0,
	"INFO":    1,
	"ERROR":   2,
	"WARNING": 3,
	"PANIC":   4,
	"FATAL":   5,
}

func (x LogLevel) String() string {
	return proto.EnumName(LogLevel_name, int32(x))
}

func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d3ae338d2e7a3df5, []int{0}
}

type OperationType int32

const (
	OperationType_QUERY        OperationType = 0
	OperationType_MUTATION     OperationType = 1
	OperationType_SUBSCRIPTION OperationType = 2
)

var OperationType_name = map[int32]string{
	0: "QUERY",
	1: "MUTATION",
	2: "SUBSCRIPTION",
}

var OperationType_value = map[string]int32{
	"QUERY":        0,
	"MUTATION":     1,
	"SUBSCRIPTION": 2,
}

func (x OperationType) String() string {
	return proto.EnumName(OperationType_name, int32(x))
}

func (OperationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d3ae338d2e7a3df5, []int{1}
}

type DataSourceKind int32

const (
	DataSourceKind_STATIC  DataSourceKind = 0
	DataSourceKind_REST    DataSourceKind = 1
	DataSourceKind_GRAPHQL DataSourceKind = 2
)

var DataSourceKind_name = map[int32]string{
	0: "STATIC",
	1: "REST",
	2: "GRAPHQL",
}

var DataSourceKind_value = map[string]int32{
	"STATIC":  0,
	"REST":    1,
	"GRAPHQL": 2,
}

func (x DataSourceKind) String() string {
	return proto.EnumName(DataSourceKind_name, int32(x))
}

func (DataSourceKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d3ae338d2e7a3df5, []int{2}
}

type HTTPMethod int32

const (
	HTTPMethod_GET    HTTPMethod = 0
	HTTPMethod_POST   HTTPMethod = 1
	HTTPMethod_PUT    HTTPMethod = 2
	HTTPMethod_DELETE HTTPMethod = 3
)

var HTTPMethod_name = map[int32]string{
	0: "GET",
	1: "POST",
	2: "PUT",
	3: "DELETE",
}

var HTTPMethod_value = map[string]int32{
	"GET":    0,
	"POST":   1,
	"PUT":    2,
	"DELETE": 3,
}

func (x HTTPMethod) String() string {
	return proto.EnumName(HTTPMethod_name, int32(x))
}

func (HTTPMethod) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d3ae338d2e7a3df5, []int{3}
}

type ArgumentSource int32

const (
	ArgumentSource_OBJECT_FIELD   ArgumentSource = 0
	ArgumentSource_FIELD_ARGUMENT ArgumentSource = 1
)

var ArgumentSource_name = map[int32]string{
	0: "OBJECT_FIELD",
	1: "FIELD_ARGUMENT",
}

var ArgumentSource_value = map[string]int32{
	"OBJECT_FIELD":   0,
	"FIELD_ARGUMENT": 1,
}

func (x ArgumentSource) String() string {
	return proto.EnumName(ArgumentSource_name, int32(x))
}

func (ArgumentSource) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d3ae338d2e7a3df5, []int{4}
}

type WunderNodeConfig struct {
	Server               *Server  `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Logging              *Logging `protobuf:"bytes,2,opt,name=logging,proto3" json:"logging,omitempty"`
	Apis                 []*Api   `protobuf:"bytes,3,rep,name=apis,proto3" json:"apis,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WunderNodeConfig) Reset()         { *m = WunderNodeConfig{} }
func (m *WunderNodeConfig) String() string { return proto.CompactTextString(m) }
func (*WunderNodeConfig) ProtoMessage()    {}
func (*WunderNodeConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3ae338d2e7a3df5, []int{0}
}

func (m *WunderNodeConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WunderNodeConfig.Unmarshal(m, b)
}
func (m *WunderNodeConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WunderNodeConfig.Marshal(b, m, deterministic)
}
func (m *WunderNodeConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WunderNodeConfig.Merge(m, src)
}
func (m *WunderNodeConfig) XXX_Size() int {
	return xxx_messageInfo_WunderNodeConfig.Size(m)
}
func (m *WunderNodeConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_WunderNodeConfig.DiscardUnknown(m)
}

var xxx_messageInfo_WunderNodeConfig proto.InternalMessageInfo

func (m *WunderNodeConfig) GetServer() *Server {
	if m != nil {
		return m.Server
	}
	return nil
}

func (m *WunderNodeConfig) GetLogging() *Logging {
	if m != nil {
		return m.Logging
	}
	return nil
}

func (m *WunderNodeConfig) GetApis() []*Api {
	if m != nil {
		return m.Apis
	}
	return nil
}

type Server struct {
	GracefulShutdownTimeout *durationpb.Duration `protobuf:"bytes,1,opt,name=gracefulShutdownTimeout,proto3" json:"gracefulShutdownTimeout,omitempty"`
	KeepAlive               *durationpb.Duration `protobuf:"bytes,2,opt,name=keepAlive,proto3" json:"keepAlive,omitempty"`
	ReadTimeout             *durationpb.Duration `protobuf:"bytes,3,opt,name=readTimeout,proto3" json:"readTimeout,omitempty"`
	WriteTimeout            *durationpb.Duration `protobuf:"bytes,4,opt,name=writeTimeout,proto3" json:"writeTimeout,omitempty"`
	IdleTimeout             *durationpb.Duration `protobuf:"bytes,5,opt,name=idleTimeout,proto3" json:"idleTimeout,omitempty"`
	Certificates            []*Certificate       `protobuf:"bytes,6,rep,name=certificates,proto3" json:"certificates,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}             `json:"-"`
	XXX_unrecognized        []byte               `json:"-"`
	XXX_sizecache           int32                `json:"-"`
}

func (m *Server) Reset()         { *m = Server{} }
func (m *Server) String() string { return proto.CompactTextString(m) }
func (*Server) ProtoMessage()    {}
func (*Server) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3ae338d2e7a3df5, []int{1}
}

func (m *Server) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Server.Unmarshal(m, b)
}
func (m *Server) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Server.Marshal(b, m, deterministic)
}
func (m *Server) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Server.Merge(m, src)
}
func (m *Server) XXX_Size() int {
	return xxx_messageInfo_Server.Size(m)
}
func (m *Server) XXX_DiscardUnknown() {
	xxx_messageInfo_Server.DiscardUnknown(m)
}

var xxx_messageInfo_Server proto.InternalMessageInfo

func (m *Server) GetGracefulShutdownTimeout() *durationpb.Duration {
	if m != nil {
		return m.GracefulShutdownTimeout
	}
	return nil
}

func (m *Server) GetKeepAlive() *durationpb.Duration {
	if m != nil {
		return m.KeepAlive
	}
	return nil
}

func (m *Server) GetReadTimeout() *durationpb.Duration {
	if m != nil {
		return m.ReadTimeout
	}
	return nil
}

func (m *Server) GetWriteTimeout() *durationpb.Duration {
	if m != nil {
		return m.WriteTimeout
	}
	return nil
}

func (m *Server) GetIdleTimeout() *durationpb.Duration {
	if m != nil {
		return m.IdleTimeout
	}
	return nil
}

func (m *Server) GetCertificates() []*Certificate {
	if m != nil {
		return m.Certificates
	}
	return nil
}

type Certificate struct {
	KeyPem               string   `protobuf:"bytes,2,opt,name=keyPem,proto3" json:"keyPem,omitempty"`
	CertPem              string   `protobuf:"bytes,3,opt,name=certPem,proto3" json:"certPem,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Certificate) Reset()         { *m = Certificate{} }
func (m *Certificate) String() string { return proto.CompactTextString(m) }
func (*Certificate) ProtoMessage()    {}
func (*Certificate) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3ae338d2e7a3df5, []int{2}
}

func (m *Certificate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Certificate.Unmarshal(m, b)
}
func (m *Certificate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Certificate.Marshal(b, m, deterministic)
}
func (m *Certificate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Certificate.Merge(m, src)
}
func (m *Certificate) XXX_Size() int {
	return xxx_messageInfo_Certificate.Size(m)
}
func (m *Certificate) XXX_DiscardUnknown() {
	xxx_messageInfo_Certificate.DiscardUnknown(m)
}

var xxx_messageInfo_Certificate proto.InternalMessageInfo

func (m *Certificate) GetKeyPem() string {
	if m != nil {
		return m.KeyPem
	}
	return ""
}

func (m *Certificate) GetCertPem() string {
	if m != nil {
		return m.CertPem
	}
	return ""
}

type Logging struct {
	Level                LogLevel `protobuf:"varint,1,opt,name=level,proto3,enum=wgpb.LogLevel" json:"level,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Logging) Reset()         { *m = Logging{} }
func (m *Logging) String() string { return proto.CompactTextString(m) }
func (*Logging) ProtoMessage()    {}
func (*Logging) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3ae338d2e7a3df5, []int{3}
}

func (m *Logging) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Logging.Unmarshal(m, b)
}
func (m *Logging) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Logging.Marshal(b, m, deterministic)
}
func (m *Logging) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Logging.Merge(m, src)
}
func (m *Logging) XXX_Size() int {
	return xxx_messageInfo_Logging.Size(m)
}
func (m *Logging) XXX_DiscardUnknown() {
	xxx_messageInfo_Logging.DiscardUnknown(m)
}

var xxx_messageInfo_Logging proto.InternalMessageInfo

func (m *Logging) GetLevel() LogLevel {
	if m != nil {
		return m.Level
	}
	return LogLevel_DEBUG
}

type Api struct {
	Hosts                 []string             `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty"`
	PathPrefix            string               `protobuf:"bytes,2,opt,name=pathPrefix,proto3" json:"pathPrefix,omitempty"`
	EngineConfiguration   *EngineConfiguration `protobuf:"bytes,3,opt,name=engineConfiguration,proto3" json:"engineConfiguration,omitempty"`
	EnableSingleFlight    bool                 `protobuf:"varint,4,opt,name=enableSingleFlight,proto3" json:"enableSingleFlight,omitempty"`
	EnableGraphqlEndpoint bool                 `protobuf:"varint,5,opt,name=enableGraphqlEndpoint,proto3" json:"enableGraphqlEndpoint,omitempty"`
	Operations            []*Operation         `protobuf:"bytes,6,rep,name=operations,proto3" json:"operations,omitempty"`
	CorsConfiguration     *CorsConfiguration   `protobuf:"bytes,7,opt,name=corsConfiguration,proto3" json:"corsConfiguration,omitempty"`
	PrimaryHost           string               `protobuf:"bytes,8,opt,name=primaryHost,proto3" json:"primaryHost,omitempty"`
	DeploymentId          string               `protobuf:"bytes,9,opt,name=deploymentId,proto3" json:"deploymentId,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}             `json:"-"`
	XXX_unrecognized      []byte               `json:"-"`
	XXX_sizecache         int32                `json:"-"`
}

func (m *Api) Reset()         { *m = Api{} }
func (m *Api) String() string { return proto.CompactTextString(m) }
func (*Api) ProtoMessage()    {}
func (*Api) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3ae338d2e7a3df5, []int{4}
}

func (m *Api) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Api.Unmarshal(m, b)
}
func (m *Api) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Api.Marshal(b, m, deterministic)
}
func (m *Api) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Api.Merge(m, src)
}
func (m *Api) XXX_Size() int {
	return xxx_messageInfo_Api.Size(m)
}
func (m *Api) XXX_DiscardUnknown() {
	xxx_messageInfo_Api.DiscardUnknown(m)
}

var xxx_messageInfo_Api proto.InternalMessageInfo

func (m *Api) GetHosts() []string {
	if m != nil {
		return m.Hosts
	}
	return nil
}

func (m *Api) GetPathPrefix() string {
	if m != nil {
		return m.PathPrefix
	}
	return ""
}

func (m *Api) GetEngineConfiguration() *EngineConfiguration {
	if m != nil {
		return m.EngineConfiguration
	}
	return nil
}

func (m *Api) GetEnableSingleFlight() bool {
	if m != nil {
		return m.EnableSingleFlight
	}
	return false
}

func (m *Api) GetEnableGraphqlEndpoint() bool {
	if m != nil {
		return m.EnableGraphqlEndpoint
	}
	return false
}

func (m *Api) GetOperations() []*Operation {
	if m != nil {
		return m.Operations
	}
	return nil
}

func (m *Api) GetCorsConfiguration() *CorsConfiguration {
	if m != nil {
		return m.CorsConfiguration
	}
	return nil
}

func (m *Api) GetPrimaryHost() string {
	if m != nil {
		return m.PrimaryHost
	}
	return ""
}

func (m *Api) GetDeploymentId() string {
	if m != nil {
		return m.DeploymentId
	}
	return ""
}

type Operation struct {
	Name                 string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Content              string         `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	OperationType        OperationType  `protobuf:"varint,3,opt,name=operationType,proto3,enum=wgpb.OperationType" json:"operationType,omitempty"`
	VariablesSchema      string         `protobuf:"bytes,4,opt,name=variablesSchema,proto3" json:"variablesSchema,omitempty"`
	ResponseSchema       string         `protobuf:"bytes,5,opt,name=responseSchema,proto3" json:"responseSchema,omitempty"`
	Mock                 *OperationMock `protobuf:"bytes,6,opt,name=mock,proto3" json:"mock,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Operation) Reset()         { *m = Operation{} }
func (m *Operation) String() string { return proto.CompactTextString(m) }
func (*Operation) ProtoMessage()    {}
func (*Operation) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3ae338d2e7a3df5, []int{5}
}

func (m *Operation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Operation.Unmarshal(m, b)
}
func (m *Operation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Operation.Marshal(b, m, deterministic)
}
func (m *Operation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Operation.Merge(m, src)
}
func (m *Operation) XXX_Size() int {
	return xxx_messageInfo_Operation.Size(m)
}
func (m *Operation) XXX_DiscardUnknown() {
	xxx_messageInfo_Operation.DiscardUnknown(m)
}

var xxx_messageInfo_Operation proto.InternalMessageInfo

func (m *Operation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Operation) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Operation) GetOperationType() OperationType {
	if m != nil {
		return m.OperationType
	}
	return OperationType_QUERY
}

func (m *Operation) GetVariablesSchema() string {
	if m != nil {
		return m.VariablesSchema
	}
	return ""
}

func (m *Operation) GetResponseSchema() string {
	if m != nil {
		return m.ResponseSchema
	}
	return ""
}

func (m *Operation) GetMock() *OperationMock {
	if m != nil {
		return m.Mock
	}
	return nil
}

type OperationMock struct {
	Enabled                           bool     `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Endpoint                          string   `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	SubscriptionPollingIntervalMillis int64    `protobuf:"varint,3,opt,name=subscriptionPollingIntervalMillis,proto3" json:"subscriptionPollingIntervalMillis,omitempty"`
	XXX_NoUnkeyedLiteral              struct{} `json:"-"`
	XXX_unrecognized                  []byte   `json:"-"`
	XXX_sizecache                     int32    `json:"-"`
}

func (m *OperationMock) Reset()         { *m = OperationMock{} }
func (m *OperationMock) String() string { return proto.CompactTextString(m) }
func (*OperationMock) ProtoMessage()    {}
func (*OperationMock) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3ae338d2e7a3df5, []int{6}
}

func (m *OperationMock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperationMock.Unmarshal(m, b)
}
func (m *OperationMock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperationMock.Marshal(b, m, deterministic)
}
func (m *OperationMock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperationMock.Merge(m, src)
}
func (m *OperationMock) XXX_Size() int {
	return xxx_messageInfo_OperationMock.Size(m)
}
func (m *OperationMock) XXX_DiscardUnknown() {
	xxx_messageInfo_OperationMock.DiscardUnknown(m)
}

var xxx_messageInfo_OperationMock proto.InternalMessageInfo

func (m *OperationMock) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *OperationMock) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *OperationMock) GetSubscriptionPollingIntervalMillis() int64 {
	if m != nil {
		return m.SubscriptionPollingIntervalMillis
	}
	return 0
}

type EngineConfiguration struct {
	DefaultFlushInterval     int64                      `protobuf:"varint,1,opt,name=defaultFlushInterval,proto3" json:"defaultFlushInterval,omitempty"`
	DatasourceConfigurations []*DataSourceConfiguration `protobuf:"bytes,2,rep,name=datasourceConfigurations,proto3" json:"datasourceConfigurations,omitempty"`
	FieldConfigurations      []*FieldConfiguration      `protobuf:"bytes,3,rep,name=fieldConfigurations,proto3" json:"fieldConfigurations,omitempty"`
	GraphqlSchema            string                     `protobuf:"bytes,4,opt,name=graphqlSchema,proto3" json:"graphqlSchema,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                   `json:"-"`
	XXX_unrecognized         []byte                     `json:"-"`
	XXX_sizecache            int32                      `json:"-"`
}

func (m *EngineConfiguration) Reset()         { *m = EngineConfiguration{} }
func (m *EngineConfiguration) String() string { return proto.CompactTextString(m) }
func (*EngineConfiguration) ProtoMessage()    {}
func (*EngineConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3ae338d2e7a3df5, []int{7}
}

func (m *EngineConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EngineConfiguration.Unmarshal(m, b)
}
func (m *EngineConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EngineConfiguration.Marshal(b, m, deterministic)
}
func (m *EngineConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EngineConfiguration.Merge(m, src)
}
func (m *EngineConfiguration) XXX_Size() int {
	return xxx_messageInfo_EngineConfiguration.Size(m)
}
func (m *EngineConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_EngineConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_EngineConfiguration proto.InternalMessageInfo

func (m *EngineConfiguration) GetDefaultFlushInterval() int64 {
	if m != nil {
		return m.DefaultFlushInterval
	}
	return 0
}

func (m *EngineConfiguration) GetDatasourceConfigurations() []*DataSourceConfiguration {
	if m != nil {
		return m.DatasourceConfigurations
	}
	return nil
}

func (m *EngineConfiguration) GetFieldConfigurations() []*FieldConfiguration {
	if m != nil {
		return m.FieldConfigurations
	}
	return nil
}

func (m *EngineConfiguration) GetGraphqlSchema() string {
	if m != nil {
		return m.GraphqlSchema
	}
	return ""
}

type DataSourceConfiguration struct {
	Kind                       DataSourceKind            `protobuf:"varint,1,opt,name=kind,proto3,enum=wgpb.DataSourceKind" json:"kind,omitempty"`
	RootNodes                  []*TypeField              `protobuf:"bytes,2,rep,name=rootNodes,proto3" json:"rootNodes,omitempty"`
	ChildNodes                 []*TypeField              `protobuf:"bytes,3,rep,name=childNodes,proto3" json:"childNodes,omitempty"`
	OverrideFieldPathFromAlias bool                      `protobuf:"varint,4,opt,name=overrideFieldPathFromAlias,proto3" json:"overrideFieldPathFromAlias,omitempty"`
	CustomRest                 *DataSourceCustom_REST    `protobuf:"bytes,5,opt,name=customRest,proto3" json:"customRest,omitempty"`
	CustomGraphql              *DataSourceCustom_GraphQL `protobuf:"bytes,6,opt,name=customGraphql,proto3" json:"customGraphql,omitempty"`
	CustomStatic               *DataSourceCustom_Static  `protobuf:"bytes,7,opt,name=customStatic,proto3" json:"customStatic,omitempty"`
	XXX_NoUnkeyedLiteral       struct{}                  `json:"-"`
	XXX_unrecognized           []byte                    `json:"-"`
	XXX_sizecache              int32                     `json:"-"`
}

func (m *DataSourceConfiguration) Reset()         { *m = DataSourceConfiguration{} }
func (m *DataSourceConfiguration) String() string { return proto.CompactTextString(m) }
func (*DataSourceConfiguration) ProtoMessage()    {}
func (*DataSourceConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3ae338d2e7a3df5, []int{8}
}

func (m *DataSourceConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataSourceConfiguration.Unmarshal(m, b)
}
func (m *DataSourceConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataSourceConfiguration.Marshal(b, m, deterministic)
}
func (m *DataSourceConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataSourceConfiguration.Merge(m, src)
}
func (m *DataSourceConfiguration) XXX_Size() int {
	return xxx_messageInfo_DataSourceConfiguration.Size(m)
}
func (m *DataSourceConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_DataSourceConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_DataSourceConfiguration proto.InternalMessageInfo

func (m *DataSourceConfiguration) GetKind() DataSourceKind {
	if m != nil {
		return m.Kind
	}
	return DataSourceKind_STATIC
}

func (m *DataSourceConfiguration) GetRootNodes() []*TypeField {
	if m != nil {
		return m.RootNodes
	}
	return nil
}

func (m *DataSourceConfiguration) GetChildNodes() []*TypeField {
	if m != nil {
		return m.ChildNodes
	}
	return nil
}

func (m *DataSourceConfiguration) GetOverrideFieldPathFromAlias() bool {
	if m != nil {
		return m.OverrideFieldPathFromAlias
	}
	return false
}

func (m *DataSourceConfiguration) GetCustomRest() *DataSourceCustom_REST {
	if m != nil {
		return m.CustomRest
	}
	return nil
}

func (m *DataSourceConfiguration) GetCustomGraphql() *DataSourceCustom_GraphQL {
	if m != nil {
		return m.CustomGraphql
	}
	return nil
}

func (m *DataSourceConfiguration) GetCustomStatic() *DataSourceCustom_Static {
	if m != nil {
		return m.CustomStatic
	}
	return nil
}

type DataSourceCustom_REST struct {
	Fetch                *FetchConfiguration            `protobuf:"bytes,1,opt,name=fetch,proto3" json:"fetch,omitempty"`
	Subscription         *RESTSubscriptionConfiguration `protobuf:"bytes,2,opt,name=subscription,proto3" json:"subscription,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *DataSourceCustom_REST) Reset()         { *m = DataSourceCustom_REST{} }
func (m *DataSourceCustom_REST) String() string { return proto.CompactTextString(m) }
func (*DataSourceCustom_REST) ProtoMessage()    {}
func (*DataSourceCustom_REST) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3ae338d2e7a3df5, []int{9}
}

func (m *DataSourceCustom_REST) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataSourceCustom_REST.Unmarshal(m, b)
}
func (m *DataSourceCustom_REST) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataSourceCustom_REST.Marshal(b, m, deterministic)
}
func (m *DataSourceCustom_REST) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataSourceCustom_REST.Merge(m, src)
}
func (m *DataSourceCustom_REST) XXX_Size() int {
	return xxx_messageInfo_DataSourceCustom_REST.Size(m)
}
func (m *DataSourceCustom_REST) XXX_DiscardUnknown() {
	xxx_messageInfo_DataSourceCustom_REST.DiscardUnknown(m)
}

var xxx_messageInfo_DataSourceCustom_REST proto.InternalMessageInfo

func (m *DataSourceCustom_REST) GetFetch() *FetchConfiguration {
	if m != nil {
		return m.Fetch
	}
	return nil
}

func (m *DataSourceCustom_REST) GetSubscription() *RESTSubscriptionConfiguration {
	if m != nil {
		return m.Subscription
	}
	return nil
}

type DataSourceCustom_GraphQL struct {
	Fetch                *FetchConfiguration               `protobuf:"bytes,1,opt,name=fetch,proto3" json:"fetch,omitempty"`
	Subscription         *GraphQLSubscriptionConfiguration `protobuf:"bytes,2,opt,name=subscription,proto3" json:"subscription,omitempty"`
	Federation           *GraphQLFederationConfiguration   `protobuf:"bytes,3,opt,name=federation,proto3" json:"federation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *DataSourceCustom_GraphQL) Reset()         { *m = DataSourceCustom_GraphQL{} }
func (m *DataSourceCustom_GraphQL) String() string { return proto.CompactTextString(m) }
func (*DataSourceCustom_GraphQL) ProtoMessage()    {}
func (*DataSourceCustom_GraphQL) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3ae338d2e7a3df5, []int{10}
}

func (m *DataSourceCustom_GraphQL) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataSourceCustom_GraphQL.Unmarshal(m, b)
}
func (m *DataSourceCustom_GraphQL) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataSourceCustom_GraphQL.Marshal(b, m, deterministic)
}
func (m *DataSourceCustom_GraphQL) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataSourceCustom_GraphQL.Merge(m, src)
}
func (m *DataSourceCustom_GraphQL) XXX_Size() int {
	return xxx_messageInfo_DataSourceCustom_GraphQL.Size(m)
}
func (m *DataSourceCustom_GraphQL) XXX_DiscardUnknown() {
	xxx_messageInfo_DataSourceCustom_GraphQL.DiscardUnknown(m)
}

var xxx_messageInfo_DataSourceCustom_GraphQL proto.InternalMessageInfo

func (m *DataSourceCustom_GraphQL) GetFetch() *FetchConfiguration {
	if m != nil {
		return m.Fetch
	}
	return nil
}

func (m *DataSourceCustom_GraphQL) GetSubscription() *GraphQLSubscriptionConfiguration {
	if m != nil {
		return m.Subscription
	}
	return nil
}

func (m *DataSourceCustom_GraphQL) GetFederation() *GraphQLFederationConfiguration {
	if m != nil {
		return m.Federation
	}
	return nil
}

type GraphQLFederationConfiguration struct {
	Enabled              bool     `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	ServiceSdl           string   `protobuf:"bytes,2,opt,name=serviceSdl,proto3" json:"serviceSdl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GraphQLFederationConfiguration) Reset()         { *m = GraphQLFederationConfiguration{} }
func (m *GraphQLFederationConfiguration) String() string { return proto.CompactTextString(m) }
func (*GraphQLFederationConfiguration) ProtoMessage()    {}
func (*GraphQLFederationConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3ae338d2e7a3df5, []int{11}
}

func (m *GraphQLFederationConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GraphQLFederationConfiguration.Unmarshal(m, b)
}
func (m *GraphQLFederationConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GraphQLFederationConfiguration.Marshal(b, m, deterministic)
}
func (m *GraphQLFederationConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphQLFederationConfiguration.Merge(m, src)
}
func (m *GraphQLFederationConfiguration) XXX_Size() int {
	return xxx_messageInfo_GraphQLFederationConfiguration.Size(m)
}
func (m *GraphQLFederationConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphQLFederationConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_GraphQLFederationConfiguration proto.InternalMessageInfo

func (m *GraphQLFederationConfiguration) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *GraphQLFederationConfiguration) GetServiceSdl() string {
	if m != nil {
		return m.ServiceSdl
	}
	return ""
}

type DataSourceCustom_Static struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataSourceCustom_Static) Reset()         { *m = DataSourceCustom_Static{} }
func (m *DataSourceCustom_Static) String() string { return proto.CompactTextString(m) }
func (*DataSourceCustom_Static) ProtoMessage()    {}
func (*DataSourceCustom_Static) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3ae338d2e7a3df5, []int{12}
}

func (m *DataSourceCustom_Static) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataSourceCustom_Static.Unmarshal(m, b)
}
func (m *DataSourceCustom_Static) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataSourceCustom_Static.Marshal(b, m, deterministic)
}
func (m *DataSourceCustom_Static) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataSourceCustom_Static.Merge(m, src)
}
func (m *DataSourceCustom_Static) XXX_Size() int {
	return xxx_messageInfo_DataSourceCustom_Static.Size(m)
}
func (m *DataSourceCustom_Static) XXX_DiscardUnknown() {
	xxx_messageInfo_DataSourceCustom_Static.DiscardUnknown(m)
}

var xxx_messageInfo_DataSourceCustom_Static proto.InternalMessageInfo

func (m *DataSourceCustom_Static) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type GraphQLSubscriptionConfiguration struct {
	Enabled              bool     `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GraphQLSubscriptionConfiguration) Reset()         { *m = GraphQLSubscriptionConfiguration{} }
func (m *GraphQLSubscriptionConfiguration) String() string { return proto.CompactTextString(m) }
func (*GraphQLSubscriptionConfiguration) ProtoMessage()    {}
func (*GraphQLSubscriptionConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3ae338d2e7a3df5, []int{13}
}

func (m *GraphQLSubscriptionConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GraphQLSubscriptionConfiguration.Unmarshal(m, b)
}
func (m *GraphQLSubscriptionConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GraphQLSubscriptionConfiguration.Marshal(b, m, deterministic)
}
func (m *GraphQLSubscriptionConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphQLSubscriptionConfiguration.Merge(m, src)
}
func (m *GraphQLSubscriptionConfiguration) XXX_Size() int {
	return xxx_messageInfo_GraphQLSubscriptionConfiguration.Size(m)
}
func (m *GraphQLSubscriptionConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphQLSubscriptionConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_GraphQLSubscriptionConfiguration proto.InternalMessageInfo

func (m *GraphQLSubscriptionConfiguration) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *GraphQLSubscriptionConfiguration) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type FetchConfiguration struct {
	Url                  string                   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Method               HTTPMethod               `protobuf:"varint,2,opt,name=method,proto3,enum=wgpb.HTTPMethod" json:"method,omitempty"`
	Header               map[string]*HTTPHeader   `protobuf:"bytes,3,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body                 string                   `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Query                []*URLQueryConfiguration `protobuf:"bytes,5,rep,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *FetchConfiguration) Reset()         { *m = FetchConfiguration{} }
func (m *FetchConfiguration) String() string { return proto.CompactTextString(m) }
func (*FetchConfiguration) ProtoMessage()    {}
func (*FetchConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3ae338d2e7a3df5, []int{14}
}

func (m *FetchConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchConfiguration.Unmarshal(m, b)
}
func (m *FetchConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchConfiguration.Marshal(b, m, deterministic)
}
func (m *FetchConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchConfiguration.Merge(m, src)
}
func (m *FetchConfiguration) XXX_Size() int {
	return xxx_messageInfo_FetchConfiguration.Size(m)
}
func (m *FetchConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_FetchConfiguration proto.InternalMessageInfo

func (m *FetchConfiguration) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *FetchConfiguration) GetMethod() HTTPMethod {
	if m != nil {
		return m.Method
	}
	return HTTPMethod_GET
}

func (m *FetchConfiguration) GetHeader() map[string]*HTTPHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *FetchConfiguration) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *FetchConfiguration) GetQuery() []*URLQueryConfiguration {
	if m != nil {
		return m.Query
	}
	return nil
}

type RESTSubscriptionConfiguration struct {
	Enabled                 bool     `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	PollingIntervalMillis   int64    `protobuf:"varint,2,opt,name=pollingIntervalMillis,proto3" json:"pollingIntervalMillis,omitempty"`
	SkipPublishSameResponse bool     `protobuf:"varint,3,opt,name=skipPublishSameResponse,proto3" json:"skipPublishSameResponse,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *RESTSubscriptionConfiguration) Reset()         { *m = RESTSubscriptionConfiguration{} }
func (m *RESTSubscriptionConfiguration) String() string { return proto.CompactTextString(m) }
func (*RESTSubscriptionConfiguration) ProtoMessage()    {}
func (*RESTSubscriptionConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3ae338d2e7a3df5, []int{15}
}

func (m *RESTSubscriptionConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RESTSubscriptionConfiguration.Unmarshal(m, b)
}
func (m *RESTSubscriptionConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RESTSubscriptionConfiguration.Marshal(b, m, deterministic)
}
func (m *RESTSubscriptionConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RESTSubscriptionConfiguration.Merge(m, src)
}
func (m *RESTSubscriptionConfiguration) XXX_Size() int {
	return xxx_messageInfo_RESTSubscriptionConfiguration.Size(m)
}
func (m *RESTSubscriptionConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_RESTSubscriptionConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_RESTSubscriptionConfiguration proto.InternalMessageInfo

func (m *RESTSubscriptionConfiguration) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *RESTSubscriptionConfiguration) GetPollingIntervalMillis() int64 {
	if m != nil {
		return m.PollingIntervalMillis
	}
	return 0
}

func (m *RESTSubscriptionConfiguration) GetSkipPublishSameResponse() bool {
	if m != nil {
		return m.SkipPublishSameResponse
	}
	return false
}

type URLQueryConfiguration struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *URLQueryConfiguration) Reset()         { *m = URLQueryConfiguration{} }
func (m *URLQueryConfiguration) String() string { return proto.CompactTextString(m) }
func (*URLQueryConfiguration) ProtoMessage()    {}
func (*URLQueryConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3ae338d2e7a3df5, []int{16}
}

func (m *URLQueryConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_URLQueryConfiguration.Unmarshal(m, b)
}
func (m *URLQueryConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_URLQueryConfiguration.Marshal(b, m, deterministic)
}
func (m *URLQueryConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_URLQueryConfiguration.Merge(m, src)
}
func (m *URLQueryConfiguration) XXX_Size() int {
	return xxx_messageInfo_URLQueryConfiguration.Size(m)
}
func (m *URLQueryConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_URLQueryConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_URLQueryConfiguration proto.InternalMessageInfo

func (m *URLQueryConfiguration) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *URLQueryConfiguration) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type HTTPHeader struct {
	Values               []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HTTPHeader) Reset()         { *m = HTTPHeader{} }
func (m *HTTPHeader) String() string { return proto.CompactTextString(m) }
func (*HTTPHeader) ProtoMessage()    {}
func (*HTTPHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3ae338d2e7a3df5, []int{17}
}

func (m *HTTPHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HTTPHeader.Unmarshal(m, b)
}
func (m *HTTPHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HTTPHeader.Marshal(b, m, deterministic)
}
func (m *HTTPHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HTTPHeader.Merge(m, src)
}
func (m *HTTPHeader) XXX_Size() int {
	return xxx_messageInfo_HTTPHeader.Size(m)
}
func (m *HTTPHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_HTTPHeader.DiscardUnknown(m)
}

var xxx_messageInfo_HTTPHeader proto.InternalMessageInfo

func (m *HTTPHeader) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

type FieldConfiguration struct {
	TypeName                          string                   `protobuf:"bytes,1,opt,name=typeName,proto3" json:"typeName,omitempty"`
	FieldName                         string                   `protobuf:"bytes,2,opt,name=fieldName,proto3" json:"fieldName,omitempty"`
	DisableDefaultFieldMapping        bool                     `protobuf:"varint,3,opt,name=disableDefaultFieldMapping,proto3" json:"disableDefaultFieldMapping,omitempty"`
	Path                              []string                 `protobuf:"bytes,4,rep,name=path,proto3" json:"path,omitempty"`
	RespectOverrideFieldPathFromAlias bool                     `protobuf:"varint,5,opt,name=respectOverrideFieldPathFromAlias,proto3" json:"respectOverrideFieldPathFromAlias,omitempty"`
	ArgumentsConfiguration            []*ArgumentConfiguration `protobuf:"bytes,6,rep,name=argumentsConfiguration,proto3" json:"argumentsConfiguration,omitempty"`
	RequiresFields                    []string                 `protobuf:"bytes,7,rep,name=requiresFields,proto3" json:"requiresFields,omitempty"`
	XXX_NoUnkeyedLiteral              struct{}                 `json:"-"`
	XXX_unrecognized                  []byte                   `json:"-"`
	XXX_sizecache                     int32                    `json:"-"`
}

func (m *FieldConfiguration) Reset()         { *m = FieldConfiguration{} }
func (m *FieldConfiguration) String() string { return proto.CompactTextString(m) }
func (*FieldConfiguration) ProtoMessage()    {}
func (*FieldConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3ae338d2e7a3df5, []int{18}
}

func (m *FieldConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldConfiguration.Unmarshal(m, b)
}
func (m *FieldConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldConfiguration.Marshal(b, m, deterministic)
}
func (m *FieldConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldConfiguration.Merge(m, src)
}
func (m *FieldConfiguration) XXX_Size() int {
	return xxx_messageInfo_FieldConfiguration.Size(m)
}
func (m *FieldConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_FieldConfiguration proto.InternalMessageInfo

func (m *FieldConfiguration) GetTypeName() string {
	if m != nil {
		return m.TypeName
	}
	return ""
}

func (m *FieldConfiguration) GetFieldName() string {
	if m != nil {
		return m.FieldName
	}
	return ""
}

func (m *FieldConfiguration) GetDisableDefaultFieldMapping() bool {
	if m != nil {
		return m.DisableDefaultFieldMapping
	}
	return false
}

func (m *FieldConfiguration) GetPath() []string {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *FieldConfiguration) GetRespectOverrideFieldPathFromAlias() bool {
	if m != nil {
		return m.RespectOverrideFieldPathFromAlias
	}
	return false
}

func (m *FieldConfiguration) GetArgumentsConfiguration() []*ArgumentConfiguration {
	if m != nil {
		return m.ArgumentsConfiguration
	}
	return nil
}

func (m *FieldConfiguration) GetRequiresFields() []string {
	if m != nil {
		return m.RequiresFields
	}
	return nil
}

type TypeField struct {
	TypeName             string   `protobuf:"bytes,1,opt,name=typeName,proto3" json:"typeName,omitempty"`
	FieldNames           []string `protobuf:"bytes,2,rep,name=fieldNames,proto3" json:"fieldNames,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TypeField) Reset()         { *m = TypeField{} }
func (m *TypeField) String() string { return proto.CompactTextString(m) }
func (*TypeField) ProtoMessage()    {}
func (*TypeField) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3ae338d2e7a3df5, []int{19}
}

func (m *TypeField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TypeField.Unmarshal(m, b)
}
func (m *TypeField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TypeField.Marshal(b, m, deterministic)
}
func (m *TypeField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TypeField.Merge(m, src)
}
func (m *TypeField) XXX_Size() int {
	return xxx_messageInfo_TypeField.Size(m)
}
func (m *TypeField) XXX_DiscardUnknown() {
	xxx_messageInfo_TypeField.DiscardUnknown(m)
}

var xxx_messageInfo_TypeField proto.InternalMessageInfo

func (m *TypeField) GetTypeName() string {
	if m != nil {
		return m.TypeName
	}
	return ""
}

func (m *TypeField) GetFieldNames() []string {
	if m != nil {
		return m.FieldNames
	}
	return nil
}

type ArgumentConfiguration struct {
	Name                 string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SourceType           ArgumentSource `protobuf:"varint,2,opt,name=sourceType,proto3,enum=wgpb.ArgumentSource" json:"sourceType,omitempty"`
	SourcePath           []string       `protobuf:"bytes,3,rep,name=sourcePath,proto3" json:"sourcePath,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ArgumentConfiguration) Reset()         { *m = ArgumentConfiguration{} }
func (m *ArgumentConfiguration) String() string { return proto.CompactTextString(m) }
func (*ArgumentConfiguration) ProtoMessage()    {}
func (*ArgumentConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3ae338d2e7a3df5, []int{20}
}

func (m *ArgumentConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArgumentConfiguration.Unmarshal(m, b)
}
func (m *ArgumentConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArgumentConfiguration.Marshal(b, m, deterministic)
}
func (m *ArgumentConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArgumentConfiguration.Merge(m, src)
}
func (m *ArgumentConfiguration) XXX_Size() int {
	return xxx_messageInfo_ArgumentConfiguration.Size(m)
}
func (m *ArgumentConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_ArgumentConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_ArgumentConfiguration proto.InternalMessageInfo

func (m *ArgumentConfiguration) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ArgumentConfiguration) GetSourceType() ArgumentSource {
	if m != nil {
		return m.SourceType
	}
	return ArgumentSource_OBJECT_FIELD
}

func (m *ArgumentConfiguration) GetSourcePath() []string {
	if m != nil {
		return m.SourcePath
	}
	return nil
}

type DataUsageMetric struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	InboundReadBytes     int64    `protobuf:"varint,2,opt,name=inboundReadBytes,proto3" json:"inboundReadBytes,omitempty"`
	InboundWriteBytes    int64    `protobuf:"varint,3,opt,name=inboundWriteBytes,proto3" json:"inboundWriteBytes,omitempty"`
	OutboundReadBytes    int64    `protobuf:"varint,4,opt,name=outboundReadBytes,proto3" json:"outboundReadBytes,omitempty"`
	OutboundWriteBytes   int64    `protobuf:"varint,5,opt,name=outboundWriteBytes,proto3" json:"outboundWriteBytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataUsageMetric) Reset()         { *m = DataUsageMetric{} }
func (m *DataUsageMetric) String() string { return proto.CompactTextString(m) }
func (*DataUsageMetric) ProtoMessage()    {}
func (*DataUsageMetric) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3ae338d2e7a3df5, []int{21}
}

func (m *DataUsageMetric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataUsageMetric.Unmarshal(m, b)
}
func (m *DataUsageMetric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataUsageMetric.Marshal(b, m, deterministic)
}
func (m *DataUsageMetric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataUsageMetric.Merge(m, src)
}
func (m *DataUsageMetric) XXX_Size() int {
	return xxx_messageInfo_DataUsageMetric.Size(m)
}
func (m *DataUsageMetric) XXX_DiscardUnknown() {
	xxx_messageInfo_DataUsageMetric.DiscardUnknown(m)
}

var xxx_messageInfo_DataUsageMetric proto.InternalMessageInfo

func (m *DataUsageMetric) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *DataUsageMetric) GetInboundReadBytes() int64 {
	if m != nil {
		return m.InboundReadBytes
	}
	return 0
}

func (m *DataUsageMetric) GetInboundWriteBytes() int64 {
	if m != nil {
		return m.InboundWriteBytes
	}
	return 0
}

func (m *DataUsageMetric) GetOutboundReadBytes() int64 {
	if m != nil {
		return m.OutboundReadBytes
	}
	return 0
}

func (m *DataUsageMetric) GetOutboundWriteBytes() int64 {
	if m != nil {
		return m.OutboundWriteBytes
	}
	return 0
}

type WunderNodeMetrics struct {
	DataUsage            []*DataUsageMetric `protobuf:"bytes,1,rep,name=dataUsage,proto3" json:"dataUsage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *WunderNodeMetrics) Reset()         { *m = WunderNodeMetrics{} }
func (m *WunderNodeMetrics) String() string { return proto.CompactTextString(m) }
func (*WunderNodeMetrics) ProtoMessage()    {}
func (*WunderNodeMetrics) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3ae338d2e7a3df5, []int{22}
}

func (m *WunderNodeMetrics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WunderNodeMetrics.Unmarshal(m, b)
}
func (m *WunderNodeMetrics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WunderNodeMetrics.Marshal(b, m, deterministic)
}
func (m *WunderNodeMetrics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WunderNodeMetrics.Merge(m, src)
}
func (m *WunderNodeMetrics) XXX_Size() int {
	return xxx_messageInfo_WunderNodeMetrics.Size(m)
}
func (m *WunderNodeMetrics) XXX_DiscardUnknown() {
	xxx_messageInfo_WunderNodeMetrics.DiscardUnknown(m)
}

var xxx_messageInfo_WunderNodeMetrics proto.InternalMessageInfo

func (m *WunderNodeMetrics) GetDataUsage() []*DataUsageMetric {
	if m != nil {
		return m.DataUsage
	}
	return nil
}

type WunderGraphConfiguration struct {
	Api                  *UserDefinedApi `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	ApiId                string          `protobuf:"bytes,2,opt,name=apiId,proto3" json:"apiId,omitempty"`
	DeploymentName       string          `protobuf:"bytes,3,opt,name=deploymentName,proto3" json:"deploymentName,omitempty"`
	EnvironmentIds       []string        `protobuf:"bytes,4,rep,name=environmentIds,proto3" json:"environmentIds,omitempty"`
	ApiName              string          `protobuf:"bytes,5,opt,name=apiName,proto3" json:"apiName,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *WunderGraphConfiguration) Reset()         { *m = WunderGraphConfiguration{} }
func (m *WunderGraphConfiguration) String() string { return proto.CompactTextString(m) }
func (*WunderGraphConfiguration) ProtoMessage()    {}
func (*WunderGraphConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3ae338d2e7a3df5, []int{23}
}

func (m *WunderGraphConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WunderGraphConfiguration.Unmarshal(m, b)
}
func (m *WunderGraphConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WunderGraphConfiguration.Marshal(b, m, deterministic)
}
func (m *WunderGraphConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WunderGraphConfiguration.Merge(m, src)
}
func (m *WunderGraphConfiguration) XXX_Size() int {
	return xxx_messageInfo_WunderGraphConfiguration.Size(m)
}
func (m *WunderGraphConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_WunderGraphConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_WunderGraphConfiguration proto.InternalMessageInfo

func (m *WunderGraphConfiguration) GetApi() *UserDefinedApi {
	if m != nil {
		return m.Api
	}
	return nil
}

func (m *WunderGraphConfiguration) GetApiId() string {
	if m != nil {
		return m.ApiId
	}
	return ""
}

func (m *WunderGraphConfiguration) GetDeploymentName() string {
	if m != nil {
		return m.DeploymentName
	}
	return ""
}

func (m *WunderGraphConfiguration) GetEnvironmentIds() []string {
	if m != nil {
		return m.EnvironmentIds
	}
	return nil
}

func (m *WunderGraphConfiguration) GetApiName() string {
	if m != nil {
		return m.ApiName
	}
	return ""
}

type UserDefinedApi struct {
	EngineConfiguration   *EngineConfiguration `protobuf:"bytes,3,opt,name=engineConfiguration,proto3" json:"engineConfiguration,omitempty"`
	EnableGraphqlEndpoint bool                 `protobuf:"varint,5,opt,name=enableGraphqlEndpoint,proto3" json:"enableGraphqlEndpoint,omitempty"`
	Operations            []*Operation         `protobuf:"bytes,6,rep,name=operations,proto3" json:"operations,omitempty"`
	CorsConfiguration     *CorsConfiguration   `protobuf:"bytes,7,opt,name=corsConfiguration,proto3" json:"corsConfiguration,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}             `json:"-"`
	XXX_unrecognized      []byte               `json:"-"`
	XXX_sizecache         int32                `json:"-"`
}

func (m *UserDefinedApi) Reset()         { *m = UserDefinedApi{} }
func (m *UserDefinedApi) String() string { return proto.CompactTextString(m) }
func (*UserDefinedApi) ProtoMessage()    {}
func (*UserDefinedApi) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3ae338d2e7a3df5, []int{24}
}

func (m *UserDefinedApi) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserDefinedApi.Unmarshal(m, b)
}
func (m *UserDefinedApi) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserDefinedApi.Marshal(b, m, deterministic)
}
func (m *UserDefinedApi) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserDefinedApi.Merge(m, src)
}
func (m *UserDefinedApi) XXX_Size() int {
	return xxx_messageInfo_UserDefinedApi.Size(m)
}
func (m *UserDefinedApi) XXX_DiscardUnknown() {
	xxx_messageInfo_UserDefinedApi.DiscardUnknown(m)
}

var xxx_messageInfo_UserDefinedApi proto.InternalMessageInfo

func (m *UserDefinedApi) GetEngineConfiguration() *EngineConfiguration {
	if m != nil {
		return m.EngineConfiguration
	}
	return nil
}

func (m *UserDefinedApi) GetEnableGraphqlEndpoint() bool {
	if m != nil {
		return m.EnableGraphqlEndpoint
	}
	return false
}

func (m *UserDefinedApi) GetOperations() []*Operation {
	if m != nil {
		return m.Operations
	}
	return nil
}

func (m *UserDefinedApi) GetCorsConfiguration() *CorsConfiguration {
	if m != nil {
		return m.CorsConfiguration
	}
	return nil
}

type CorsConfiguration struct {
	// AllowedOrigins is a list of origins a cross-domain request can be executed from.
	// If the special "*" value is present in the list, all origins will be allowed.
	// An origin may contain a wildcard (*) to replace 0 or more characters
	// (i.e.: http://*.domain.com). Usage of wildcards implies a small performance penalty.
	// Only one wildcard can be used per origin.
	// Default value is ["*"]
	AllowedOrigins []string `protobuf:"bytes,1,rep,name=allowedOrigins,proto3" json:"allowedOrigins,omitempty"`
	// AllowedMethods is a list of methods the client is allowed to use with
	// cross-domain requests. Default value is simple methods (HEAD, GET and POST).
	AllowedMethods []string `protobuf:"bytes,2,rep,name=allowedMethods,proto3" json:"allowedMethods,omitempty"`
	// AllowedHeaders is list of non simple headers the client is allowed to use with
	// cross-domain requests.
	// If the special "*" value is present in the list, all headers will be allowed.
	// Default value is [] but "Origin" is always appended to the list.
	AllowedHeaders []string `protobuf:"bytes,3,rep,name=allowedHeaders,proto3" json:"allowedHeaders,omitempty"`
	// ExposedHeaders indicates which headers are safe to expose to the API of a CORS
	// API specification
	ExposedHeaders []string `protobuf:"bytes,4,rep,name=exposedHeaders,proto3" json:"exposedHeaders,omitempty"`
	// MaxAge indicates how long (in seconds) the results of a preflight request
	// can be cached
	MaxAge int64 `protobuf:"varint,5,opt,name=maxAge,proto3" json:"maxAge,omitempty"`
	// AllowCredentials indicates whether the request can include user credentials like
	// cookies, HTTP authentication or client side SSL certificates.
	AllowCredentials     bool     `protobuf:"varint,6,opt,name=allowCredentials,proto3" json:"allowCredentials,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CorsConfiguration) Reset()         { *m = CorsConfiguration{} }
func (m *CorsConfiguration) String() string { return proto.CompactTextString(m) }
func (*CorsConfiguration) ProtoMessage()    {}
func (*CorsConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3ae338d2e7a3df5, []int{25}
}

func (m *CorsConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CorsConfiguration.Unmarshal(m, b)
}
func (m *CorsConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CorsConfiguration.Marshal(b, m, deterministic)
}
func (m *CorsConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CorsConfiguration.Merge(m, src)
}
func (m *CorsConfiguration) XXX_Size() int {
	return xxx_messageInfo_CorsConfiguration.Size(m)
}
func (m *CorsConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_CorsConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_CorsConfiguration proto.InternalMessageInfo

func (m *CorsConfiguration) GetAllowedOrigins() []string {
	if m != nil {
		return m.AllowedOrigins
	}
	return nil
}

func (m *CorsConfiguration) GetAllowedMethods() []string {
	if m != nil {
		return m.AllowedMethods
	}
	return nil
}

func (m *CorsConfiguration) GetAllowedHeaders() []string {
	if m != nil {
		return m.AllowedHeaders
	}
	return nil
}

func (m *CorsConfiguration) GetExposedHeaders() []string {
	if m != nil {
		return m.ExposedHeaders
	}
	return nil
}

func (m *CorsConfiguration) GetMaxAge() int64 {
	if m != nil {
		return m.MaxAge
	}
	return 0
}

func (m *CorsConfiguration) GetAllowCredentials() bool {
	if m != nil {
		return m.AllowCredentials
	}
	return false
}

func init() {
	proto.RegisterEnum("wgpb.LogLevel", LogLevel_name, LogLevel_value)
	proto.RegisterEnum("wgpb.OperationType", OperationType_name, OperationType_value)
	proto.RegisterEnum("wgpb.DataSourceKind", DataSourceKind_name, DataSourceKind_value)
	proto.RegisterEnum("wgpb.HTTPMethod", HTTPMethod_name, HTTPMethod_value)
	proto.RegisterEnum("wgpb.ArgumentSource", ArgumentSource_name, ArgumentSource_value)
	proto.RegisterType((*WunderNodeConfig)(nil), "wgpb.WunderNodeConfig")
	proto.RegisterType((*Server)(nil), "wgpb.Server")
	proto.RegisterType((*Certificate)(nil), "wgpb.Certificate")
	proto.RegisterType((*Logging)(nil), "wgpb.Logging")
	proto.RegisterType((*Api)(nil), "wgpb.Api")
	proto.RegisterType((*Operation)(nil), "wgpb.Operation")
	proto.RegisterType((*OperationMock)(nil), "wgpb.OperationMock")
	proto.RegisterType((*EngineConfiguration)(nil), "wgpb.EngineConfiguration")
	proto.RegisterType((*DataSourceConfiguration)(nil), "wgpb.DataSourceConfiguration")
	proto.RegisterType((*DataSourceCustom_REST)(nil), "wgpb.DataSourceCustom_REST")
	proto.RegisterType((*DataSourceCustom_GraphQL)(nil), "wgpb.DataSourceCustom_GraphQL")
	proto.RegisterType((*GraphQLFederationConfiguration)(nil), "wgpb.GraphQLFederationConfiguration")
	proto.RegisterType((*DataSourceCustom_Static)(nil), "wgpb.DataSourceCustom_Static")
	proto.RegisterType((*GraphQLSubscriptionConfiguration)(nil), "wgpb.GraphQLSubscriptionConfiguration")
	proto.RegisterType((*FetchConfiguration)(nil), "wgpb.FetchConfiguration")
	proto.RegisterMapType((map[string]*HTTPHeader)(nil), "wgpb.FetchConfiguration.HeaderEntry")
	proto.RegisterType((*RESTSubscriptionConfiguration)(nil), "wgpb.RESTSubscriptionConfiguration")
	proto.RegisterType((*URLQueryConfiguration)(nil), "wgpb.URLQueryConfiguration")
	proto.RegisterType((*HTTPHeader)(nil), "wgpb.HTTPHeader")
	proto.RegisterType((*FieldConfiguration)(nil), "wgpb.FieldConfiguration")
	proto.RegisterType((*TypeField)(nil), "wgpb.TypeField")
	proto.RegisterType((*ArgumentConfiguration)(nil), "wgpb.ArgumentConfiguration")
	proto.RegisterType((*DataUsageMetric)(nil), "wgpb.DataUsageMetric")
	proto.RegisterType((*WunderNodeMetrics)(nil), "wgpb.WunderNodeMetrics")
	proto.RegisterType((*WunderGraphConfiguration)(nil), "wgpb.WunderGraphConfiguration")
	proto.RegisterType((*UserDefinedApi)(nil), "wgpb.UserDefinedApi")
	proto.RegisterType((*CorsConfiguration)(nil), "wgpb.CorsConfiguration")
}

func init() { proto.RegisterFile("wundernode_config.proto", fileDescriptor_d3ae338d2e7a3df5) }

var fileDescriptor_d3ae338d2e7a3df5 = []byte{
	// 1930 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x58, 0x4b, 0x6f, 0x1b, 0xc9,
	0xf1, 0xf7, 0x70, 0x48, 0x8a, 0x2c, 0x49, 0xf4, 0xa8, 0x6d, 0xad, 0xf8, 0xf7, 0x3f, 0x16, 0x94,
	0x89, 0xe0, 0x15, 0x84, 0x2c, 0x8d, 0xc8, 0x4e, 0xb2, 0xd9, 0xcd, 0x03, 0x94, 0x48, 0x49, 0xb4,
	0x29, 0x8a, 0x6e, 0x92, 0x30, 0x76, 0x2f, 0xc6, 0x88, 0xd3, 0x24, 0x1b, 0x1a, 0x4e, 0x8f, 0xe7,
	0x21, 0x99, 0xb7, 0xe4, 0x92, 0x4b, 0x2e, 0x01, 0x02, 0xe4, 0x03, 0xe4, 0xb6, 0x40, 0x3e, 0x45,
	0x3e, 0x47, 0xf2, 0x11, 0x82, 0x1c, 0x73, 0x0d, 0xfa, 0x31, 0xe4, 0x0c, 0x5f, 0x4a, 0x80, 0x5c,
	0x72, 0x9b, 0xae, 0xfa, 0x55, 0x75, 0xbd, 0xba, 0xaa, 0x7b, 0x60, 0xef, 0x3e, 0x72, 0x6d, 0xe2,
	0xbb, 0xcc, 0x26, 0x1f, 0xfa, 0xcc, 0x1d, 0xd0, 0x61, 0xc5, 0xf3, 0x59, 0xc8, 0x50, 0xf6, 0x7e,
	0xe8, 0xdd, 0x3c, 0xdb, 0x1f, 0x32, 0x36, 0x74, 0xc8, 0x4b, 0x41, 0xbb, 0x89, 0x06, 0x2f, 0xed,
	0xc8, 0xb7, 0x42, 0xca, 0x5c, 0x89, 0x32, 0x7f, 0xad, 0x81, 0xf1, 0x5e, 0x68, 0x68, 0x31, 0x9b,
	0x9c, 0x09, 0x05, 0xe8, 0x10, 0xf2, 0x01, 0xf1, 0xef, 0x88, 0x5f, 0xd6, 0x0e, 0xb4, 0xa3, 0xcd,
	0x93, 0xad, 0x0a, 0xd7, 0x55, 0xe9, 0x08, 0x1a, 0x56, 0x3c, 0xf4, 0x39, 0x6c, 0x38, 0x6c, 0x38,
	0xa4, 0xee, 0xb0, 0x9c, 0x11, 0xb0, 0x6d, 0x09, 0x6b, 0x4a, 0x22, 0x8e, 0xb9, 0xe8, 0x39, 0x64,
	0x2d, 0x8f, 0x06, 0x65, 0xfd, 0x40, 0x3f, 0xda, 0x3c, 0x29, 0x4a, 0x54, 0xd5, 0xa3, 0x58, 0x90,
	0xcd, 0xdf, 0xea, 0x90, 0x97, 0xaa, 0x51, 0x07, 0xf6, 0x86, 0xbe, 0xd5, 0x27, 0x83, 0xc8, 0xe9,
	0x8c, 0xa2, 0xd0, 0x66, 0xf7, 0x6e, 0x97, 0x8e, 0x09, 0x8b, 0x42, 0x65, 0xc9, 0xff, 0x55, 0xa4,
	0x3f, 0x95, 0xd8, 0x9f, 0x4a, 0x4d, 0xf9, 0x83, 0x57, 0x49, 0xa2, 0x9f, 0x42, 0xf1, 0x96, 0x10,
	0xaf, 0xea, 0xd0, 0x3b, 0xa2, 0x2c, 0x5d, 0xa3, 0x66, 0x86, 0x45, 0x5f, 0xc3, 0xa6, 0x4f, 0x2c,
	0x3b, 0xb6, 0x40, 0x7f, 0x48, 0x34, 0x89, 0x46, 0xbf, 0x80, 0xad, 0x7b, 0x9f, 0x86, 0x24, 0x96,
	0xce, 0x3e, 0x24, 0x9d, 0x82, 0xf3, 0xbd, 0xa9, 0xed, 0x4c, 0xa5, 0x73, 0x0f, 0xee, 0x9d, 0x40,
	0xa3, 0x1f, 0xc3, 0x56, 0x9f, 0xf8, 0x21, 0x1d, 0xd0, 0xbe, 0x15, 0x92, 0xa0, 0x9c, 0x17, 0x81,
	0xdf, 0x91, 0x81, 0x3f, 0x9b, 0x71, 0x70, 0x0a, 0x66, 0xfe, 0x0a, 0x36, 0x13, 0x4c, 0xf4, 0x19,
	0xe4, 0x6f, 0xc9, 0xa4, 0x4d, 0xc6, 0x22, 0x68, 0x45, 0xac, 0x56, 0xa8, 0x0c, 0x1b, 0x5c, 0x8c,
	0x33, 0x74, 0xc1, 0x88, 0x97, 0xe6, 0x4b, 0xd8, 0x50, 0xc9, 0x47, 0x87, 0x90, 0x73, 0xc8, 0x1d,
	0x71, 0x44, 0xde, 0x4a, 0x27, 0xa5, 0x69, 0x69, 0x34, 0x39, 0x15, 0x4b, 0xa6, 0xf9, 0x67, 0x1d,
	0xf4, 0xaa, 0x47, 0xd1, 0x53, 0xc8, 0x8d, 0x58, 0x10, 0x06, 0x65, 0xed, 0x40, 0x3f, 0x2a, 0x62,
	0xb9, 0x40, 0xfb, 0x00, 0x9e, 0x15, 0x8e, 0xda, 0x3e, 0x19, 0xd0, 0x4f, 0xca, 0x88, 0x04, 0x05,
	0xbd, 0x85, 0x27, 0xc4, 0x1d, 0x52, 0x57, 0x95, 0xad, 0x0a, 0xc5, 0x34, 0x4f, 0x62, 0xc7, 0xfa,
	0x22, 0x00, 0x2f, 0x93, 0x42, 0x15, 0x40, 0xc4, 0xb5, 0x6e, 0x1c, 0xd2, 0xa1, 0xee, 0xd0, 0x21,
	0xe7, 0x0e, 0x1d, 0x8e, 0x64, 0xd6, 0x0a, 0x78, 0x09, 0x07, 0xbd, 0x86, 0x5d, 0x49, 0xbd, 0xf0,
	0x2d, 0x6f, 0xf4, 0xd1, 0xa9, 0xbb, 0xb6, 0xc7, 0xa8, 0x2b, 0x53, 0x55, 0xc0, 0xcb, 0x99, 0xe8,
	0x25, 0x00, 0xf3, 0x88, 0xdc, 0x32, 0xce, 0xcb, 0x63, 0x69, 0xe9, 0x75, 0x4c, 0xc7, 0x09, 0x08,
	0xaa, 0xc3, 0x4e, 0x9f, 0xf9, 0x41, 0xda, 0xc3, 0x0d, 0xe1, 0xe1, 0x9e, 0xca, 0xe7, 0x3c, 0x1b,
	0x2f, 0x4a, 0xa0, 0x03, 0xd8, 0xf4, 0x7c, 0x3a, 0xb6, 0xfc, 0xc9, 0x25, 0x0b, 0xc2, 0x72, 0x41,
	0xc4, 0x32, 0x49, 0x42, 0x26, 0x6c, 0xd9, 0xc4, 0x73, 0xd8, 0x64, 0x4c, 0xdc, 0xb0, 0x61, 0x97,
	0x8b, 0x02, 0x92, 0xa2, 0x99, 0xff, 0xd0, 0xa0, 0x38, 0x35, 0x13, 0x21, 0xc8, 0xba, 0xd6, 0x98,
	0x88, 0x0c, 0x17, 0xb1, 0xf8, 0x16, 0xb5, 0xc1, 0xdc, 0x90, 0xb8, 0xa1, 0xca, 0x57, 0xbc, 0x44,
	0x3f, 0x83, 0xed, 0xa9, 0x5b, 0xdd, 0x89, 0x47, 0x44, 0x9a, 0x4a, 0x27, 0x4f, 0xe6, 0x9c, 0xe7,
	0x2c, 0x9c, 0x46, 0xa2, 0x23, 0x78, 0x7c, 0x67, 0xf9, 0x94, 0xc7, 0x33, 0xe8, 0xf4, 0x47, 0x64,
	0x6c, 0x89, 0xbc, 0x14, 0xf1, 0x3c, 0x19, 0xbd, 0x80, 0x92, 0x4f, 0x02, 0x8f, 0xb9, 0x01, 0x51,
	0xc0, 0x9c, 0x00, 0xce, 0x51, 0xd1, 0xe7, 0x90, 0x1d, 0xb3, 0xfe, 0x6d, 0x39, 0x2f, 0x02, 0x39,
	0x6f, 0xc3, 0x15, 0xeb, 0xdf, 0x62, 0x01, 0x30, 0xff, 0xa0, 0xc1, 0x76, 0x8a, 0xce, 0x3d, 0x94,
	0xa9, 0xb5, 0x85, 0xe3, 0x05, 0x1c, 0x2f, 0xd1, 0x33, 0x28, 0x90, 0xb8, 0x08, 0xa4, 0xf3, 0xd3,
	0x35, 0x6a, 0xc2, 0xf7, 0x83, 0xe8, 0x26, 0xe8, 0xfb, 0xd4, 0xe3, 0x9a, 0xda, 0xcc, 0x71, 0xa8,
	0x3b, 0x6c, 0xb8, 0x21, 0xf1, 0xef, 0x2c, 0xe7, 0x8a, 0x3a, 0x8e, 0xe8, 0x8f, 0xda, 0x91, 0x8e,
	0x1f, 0x06, 0x9a, 0x7f, 0xcc, 0xc0, 0x93, 0x25, 0x85, 0x8d, 0x4e, 0xe0, 0xa9, 0x4d, 0x06, 0x56,
	0xe4, 0x84, 0xe7, 0x4e, 0x14, 0x8c, 0x62, 0x29, 0x61, 0xa8, 0x8e, 0x97, 0xf2, 0xd0, 0x37, 0x50,
	0xb6, 0xad, 0xd0, 0x0a, 0x58, 0xe4, 0xf7, 0xd3, 0xea, 0x82, 0x72, 0x46, 0xd4, 0xe7, 0x73, 0x19,
	0x9e, 0x9a, 0x15, 0x5a, 0x9d, 0x45, 0x14, 0x5e, 0x29, 0x8e, 0xde, 0xc0, 0x93, 0x01, 0x25, 0x8e,
	0x3d, 0xa7, 0x55, 0x8e, 0x81, 0xb2, 0xd4, 0x7a, 0xbe, 0x00, 0xc0, 0xcb, 0x84, 0xd0, 0x21, 0x6c,
	0x0f, 0xe5, 0x59, 0x4a, 0x55, 0x40, 0x9a, 0x68, 0x7e, 0xa7, 0xc3, 0xde, 0x0a, 0x3b, 0xd1, 0x11,
	0x64, 0x6f, 0xa9, 0x6b, 0xab, 0x86, 0xf4, 0x74, 0xde, 0xa9, 0xb7, 0xd4, 0xb5, 0xb1, 0x40, 0xa0,
	0x2f, 0xa0, 0xe8, 0x33, 0x16, 0xf2, 0x81, 0x18, 0xc7, 0x40, 0x9d, 0x51, 0x5e, 0x8e, 0xc2, 0x62,
	0x3c, 0x43, 0xf0, 0x33, 0xdd, 0x1f, 0x51, 0xc7, 0x96, 0x78, 0x7d, 0x39, 0x3e, 0x01, 0x41, 0xbf,
	0x84, 0x67, 0xec, 0x8e, 0xf8, 0x3e, 0xb5, 0x25, 0xb3, 0x6d, 0x85, 0xa3, 0x73, 0x9f, 0x8d, 0xab,
	0x0e, 0xb5, 0x02, 0xd5, 0x72, 0xd6, 0x20, 0xd0, 0xd7, 0x00, 0xfd, 0x28, 0x08, 0xd9, 0x18, 0x93,
	0x20, 0x1e, 0x0d, 0xff, 0xbf, 0x90, 0x24, 0x81, 0xf8, 0x80, 0xeb, 0x9d, 0x2e, 0x4e, 0xc0, 0x51,
	0x0d, 0xb6, 0xe5, 0x4a, 0xb5, 0x26, 0x75, 0x06, 0xf6, 0x57, 0xc8, 0x0b, 0xd4, 0xbb, 0x26, 0x4e,
	0x0b, 0xa1, 0x2a, 0x6c, 0x49, 0x42, 0x27, 0xb4, 0x42, 0xda, 0x57, 0x1d, 0xe9, 0xf9, 0x0a, 0x25,
	0x12, 0x84, 0x53, 0x22, 0xe6, 0xef, 0x35, 0xd8, 0x5d, 0x6a, 0x2e, 0xaa, 0x40, 0x6e, 0x40, 0xc2,
	0xfe, 0x48, 0xcd, 0xfc, 0xb8, 0x52, 0x38, 0x29, 0x5d, 0x29, 0x12, 0x86, 0x2e, 0x60, 0x2b, 0x79,
	0x66, 0xd4, 0x8c, 0xff, 0x81, 0x14, 0xe3, 0x1a, 0x3b, 0x09, 0x6e, 0x5a, 0x43, 0x4a, 0xd0, 0xfc,
	0xab, 0x06, 0xe5, 0x55, 0x11, 0xf8, 0x8f, 0xad, 0x7a, 0xb3, 0xd4, 0xaa, 0x17, 0x52, 0x4c, 0x29,
	0xfd, 0x37, 0x0d, 0x43, 0x35, 0x80, 0x01, 0xb1, 0x49, 0x6a, 0xc0, 0x1d, 0xa6, 0x34, 0x9d, 0x4f,
	0xd9, 0x69, 0x3d, 0x09, 0x39, 0xf3, 0x5b, 0xd8, 0x5f, 0x8f, 0x5e, 0xd3, 0xdc, 0xf6, 0x01, 0xf8,
	0xb5, 0x8f, 0xf6, 0x49, 0xc7, 0x76, 0xe2, 0x59, 0x3c, 0xa3, 0x98, 0x5f, 0xa4, 0x0e, 0x5e, 0x32,
	0xed, 0x7c, 0x4e, 0xf0, 0x16, 0x11, 0xcf, 0x09, 0xfe, 0x6d, 0xb6, 0xe0, 0xe0, 0xa1, 0x10, 0xac,
	0x31, 0xc6, 0x00, 0x3d, 0xf2, 0x63, 0x2b, 0xf8, 0xa7, 0xf9, 0xa7, 0x0c, 0xa0, 0xc5, 0x54, 0xc4,
	0x40, 0x6d, 0x0a, 0x44, 0x47, 0x90, 0x1f, 0x93, 0x70, 0xc4, 0x6c, 0x21, 0x5d, 0x3a, 0x31, 0x64,
	0x14, 0x2f, 0xbb, 0xdd, 0xf6, 0x95, 0xa0, 0x63, 0xc5, 0x47, 0x3f, 0x87, 0xfc, 0x88, 0x58, 0x36,
	0xf1, 0xd5, 0x91, 0x3e, 0x5c, 0x95, 0xf0, 0xca, 0xa5, 0x80, 0xd5, 0xdd, 0xd0, 0x9f, 0x60, 0x25,
	0xc3, 0x9d, 0xbe, 0x61, 0xf6, 0x44, 0xb5, 0x29, 0xf1, 0x8d, 0x7e, 0x04, 0xb9, 0x8f, 0x11, 0xf1,
	0x27, 0xe5, 0x9c, 0x50, 0xa8, 0x8e, 0x6c, 0x0f, 0x37, 0xdf, 0x71, 0xea, 0x5c, 0x11, 0x09, 0xe4,
	0xb3, 0xb7, 0xb0, 0x99, 0xd0, 0xce, 0xfd, 0xb9, 0x25, 0x93, 0xd8, 0x9f, 0x5b, 0x32, 0x41, 0x2f,
	0x20, 0x77, 0x67, 0x39, 0x51, 0x7c, 0xb1, 0x4d, 0xb8, 0x23, 0xe5, 0xb0, 0x64, 0x7f, 0x95, 0xf9,
	0x52, 0x33, 0xbf, 0xd3, 0xe0, 0xf9, 0xda, 0xe3, 0xb0, 0x26, 0xe4, 0xaf, 0x61, 0xd7, 0x5b, 0x3a,
	0xb4, 0x32, 0x62, 0xb6, 0x2c, 0x67, 0xa2, 0x2f, 0x61, 0x2f, 0xb8, 0xa5, 0x5e, 0x3b, 0xba, 0x71,
	0x68, 0x30, 0xea, 0x58, 0x63, 0x82, 0xd5, 0x20, 0x16, 0x45, 0x5c, 0xc0, 0xab, 0xd8, 0x66, 0x15,
	0x76, 0x97, 0x06, 0x66, 0xe9, 0xad, 0xe3, 0x69, 0x32, 0x08, 0x45, 0xe5, 0xb2, 0x79, 0x08, 0x30,
	0x8b, 0x03, 0xbf, 0xcd, 0x0a, 0x72, 0x7c, 0xc7, 0x54, 0x2b, 0xf3, 0xef, 0xbc, 0x72, 0x16, 0x06,
	0x0e, 0x1f, 0xe6, 0xe1, 0xc4, 0x23, 0xad, 0xd9, 0x56, 0xd3, 0x35, 0xfa, 0x1e, 0x14, 0xc5, 0x88,
	0x12, 0x4c, 0xb9, 0xe5, 0x8c, 0xc0, 0xbb, 0xbb, 0x4d, 0x03, 0x1e, 0xb5, 0x9a, 0x9a, 0xb7, 0x9c,
	0x75, 0x65, 0x79, 0x1e, 0x7f, 0x29, 0x49, 0xb7, 0xd7, 0x20, 0xb8, 0x83, 0xfc, 0x8e, 0x5b, 0xce,
	0x0a, 0x33, 0xc5, 0x37, 0xbf, 0x3e, 0xf0, 0x1b, 0x0c, 0xe9, 0x87, 0xd7, 0xab, 0x07, 0x87, 0xbc,
	0x78, 0x3e, 0x0c, 0x44, 0x1d, 0xf8, 0xcc, 0xf2, 0x87, 0x11, 0xbf, 0xd4, 0xcd, 0x5d, 0x2c, 0xf3,
	0xc9, 0xc2, 0xac, 0x2a, 0x4c, 0xba, 0x30, 0x57, 0x88, 0xca, 0xab, 0xd7, 0xc7, 0x88, 0xfa, 0x24,
	0x10, 0x5b, 0x06, 0xe5, 0x0d, 0xe1, 0xc0, 0x1c, 0xd5, 0xbc, 0x80, 0xe2, 0x74, 0x2a, 0xae, 0x8d,
	0xf2, 0x3e, 0xc0, 0x34, 0xa8, 0x72, 0x0c, 0x17, 0x71, 0x82, 0x62, 0xfe, 0x46, 0x83, 0xdd, 0xa5,
	0x26, 0x2e, 0x2d, 0x91, 0xd7, 0x00, 0xf2, 0x8e, 0x22, 0xee, 0x9e, 0x99, 0xe4, 0x1d, 0x20, 0x56,
	0x22, 0x7b, 0x17, 0x4e, 0xe0, 0x44, 0xd7, 0x13, 0x2b, 0x1e, 0x40, 0xd1, 0x07, 0x8a, 0x38, 0x41,
	0x31, 0xff, 0xa6, 0xc1, 0x63, 0xde, 0xf6, 0x7a, 0x81, 0x35, 0x24, 0x57, 0x24, 0xf4, 0x65, 0xbb,
	0xe3, 0xcf, 0x97, 0x78, 0x77, 0xfe, 0x8d, 0x8e, 0xc1, 0xa0, 0xee, 0x0d, 0x8b, 0x5c, 0x1b, 0x13,
	0xcb, 0x3e, 0x9d, 0x84, 0x24, 0x3e, 0x38, 0x0b, 0x74, 0xf4, 0x43, 0xd8, 0x51, 0xb4, 0xf7, 0xfc,
	0x41, 0x28, 0xc1, 0xf2, 0x6a, 0xb8, 0xc8, 0xe0, 0x68, 0x16, 0x85, 0x73, 0xaa, 0xb3, 0x12, 0xbd,
	0xc0, 0xe0, 0x8f, 0x9c, 0x98, 0x98, 0x50, 0x9e, 0x13, 0xf0, 0x25, 0x1c, 0xf3, 0x12, 0x76, 0x66,
	0x3f, 0x07, 0xa4, 0x7f, 0x01, 0x7a, 0x05, 0x45, 0x3b, 0xf6, 0x59, 0x1c, 0xa6, 0xcd, 0x93, 0xdd,
	0xd9, 0xe0, 0x4f, 0x84, 0x02, 0xcf, 0x70, 0xe6, 0x5f, 0x34, 0x28, 0x4b, 0x55, 0xa2, 0xef, 0xcf,
	0xd7, 0x8e, 0x6e, 0x79, 0x54, 0x0d, 0x56, 0x95, 0x95, 0x5e, 0x40, 0xfc, 0x1a, 0x19, 0x50, 0x97,
	0xd8, 0x55, 0x8f, 0x62, 0x0e, 0xe0, 0xe7, 0xdc, 0xf2, 0x68, 0xc3, 0x8e, 0xcf, 0xb9, 0x58, 0xf0,
	0xca, 0x9b, 0xbd, 0x52, 0x44, 0x29, 0xc9, 0x67, 0xe9, 0x1c, 0x95, 0xe3, 0x88, 0x7b, 0x47, 0x7d,
	0xe6, 0xca, 0xe7, 0x4c, 0xa0, 0x8e, 0xd8, 0x1c, 0x95, 0x37, 0x41, 0xcb, 0xa3, 0x42, 0x91, 0x7c,
	0x3d, 0xc4, 0x4b, 0xf3, 0x77, 0x19, 0x28, 0xa5, 0xed, 0xfa, 0xef, 0xbe, 0x41, 0xff, 0xa7, 0xde,
	0x94, 0xe6, 0x3f, 0x35, 0xd8, 0x59, 0x00, 0xf2, 0x28, 0x5b, 0x8e, 0xc3, 0xee, 0x89, 0x7d, 0xed,
	0xd3, 0x21, 0x75, 0xe3, 0x7e, 0x3b, 0x47, 0x4d, 0xe0, 0xe4, 0xdc, 0x8d, 0x8f, 0xf8, 0x1c, 0x35,
	0x81, 0x93, 0x8d, 0x3c, 0x50, 0xc7, 0x70, 0x8e, 0x2a, 0xb2, 0xfb, 0xc9, 0x63, 0xc1, 0x0c, 0x17,
	0x67, 0x37, 0x45, 0xe5, 0x73, 0x60, 0x6c, 0x7d, 0xaa, 0x0e, 0x89, 0x2a, 0x7b, 0xb5, 0xe2, 0x47,
	0x54, 0x68, 0x3c, 0xf3, 0x89, 0x4d, 0xdc, 0x90, 0x5a, 0x4e, 0x20, 0xae, 0xc6, 0x05, 0xbc, 0x40,
	0x3f, 0xbe, 0x82, 0x42, 0xfc, 0x27, 0x03, 0x15, 0x21, 0x57, 0xab, 0x9f, 0xf6, 0x2e, 0x8c, 0x47,
	0xa8, 0x00, 0xd9, 0x46, 0xeb, 0xfc, 0xda, 0xd0, 0x38, 0xb1, 0x8e, 0xf1, 0x35, 0x36, 0x32, 0x68,
	0x13, 0x36, 0xde, 0x57, 0x71, 0xab, 0xd1, 0xba, 0x30, 0x74, 0x4e, 0x6f, 0x57, 0x5b, 0x8d, 0x33,
	0x23, 0xcb, 0x3f, 0xcf, 0xab, 0xdd, 0x6a, 0xd3, 0xc8, 0x1d, 0x7f, 0x95, 0x78, 0x63, 0x8a, 0xb6,
	0x53, 0x84, 0xdc, 0xbb, 0x5e, 0x1d, 0x7f, 0x63, 0x3c, 0x42, 0x5b, 0x50, 0xb8, 0xea, 0x75, 0xab,
	0xdd, 0xc6, 0x75, 0xcb, 0xd0, 0x90, 0x01, 0x5b, 0x9d, 0xde, 0x69, 0xe7, 0x0c, 0x37, 0xda, 0x82,
	0x92, 0x39, 0x7e, 0x05, 0xa5, 0xf4, 0x1b, 0x06, 0x01, 0xe4, 0x3b, 0x5c, 0xe0, 0x4c, 0x5a, 0xc4,
	0x07, 0xbe, 0xa1, 0x71, 0x33, 0x2e, 0x70, 0xb5, 0x7d, 0xf9, 0xae, 0x69, 0x64, 0x8e, 0x5f, 0xcb,
	0xc9, 0x28, 0x43, 0x8c, 0x36, 0x40, 0xbf, 0xa8, 0x77, 0x25, 0xba, 0x7d, 0x2d, 0xd0, 0x1b, 0xa0,
	0xb7, 0x7b, 0x5d, 0x23, 0xc3, 0x95, 0xd5, 0xea, 0xcd, 0x7a, 0xb7, 0x6e, 0xe8, 0xc7, 0x3f, 0x81,
	0x52, 0xba, 0x55, 0x72, 0x73, 0xae, 0x4f, 0xdf, 0xd4, 0xcf, 0xba, 0x1f, 0xce, 0x1b, 0xf5, 0x66,
	0xcd, 0x78, 0x84, 0x10, 0x94, 0xc4, 0xe7, 0x87, 0x2a, 0xbe, 0xe8, 0x5d, 0xd5, 0x5b, 0x5d, 0x43,
	0x3b, 0xcd, 0x7f, 0x2b, 0x7e, 0x45, 0xde, 0xe4, 0xc5, 0x5f, 0xab, 0x57, 0xff, 0x0a, 0x00, 0x00,
	0xff, 0xff, 0x5c, 0x78, 0x8b, 0x2a, 0xb2, 0x14, 0x00, 0x00,
}
