// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wundernode_config.proto

package wgpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LogLevel int32

const (
	LogLevel_DEBUG   LogLevel = 0
	LogLevel_INFO    LogLevel = 1
	LogLevel_ERROR   LogLevel = 2
	LogLevel_WARNING LogLevel = 3
	LogLevel_PANIC   LogLevel = 4
	LogLevel_FATAL   LogLevel = 5
)

var LogLevel_name = map[int32]string{
	0: "DEBUG",
	1: "INFO",
	2: "ERROR",
	3: "WARNING",
	4: "PANIC",
	5: "FATAL",
}

var LogLevel_value = map[string]int32{
	"DEBUG":   0,
	"INFO":    1,
	"ERROR":   2,
	"WARNING": 3,
	"PANIC":   4,
	"FATAL":   5,
}

func (x LogLevel) String() string {
	return proto.EnumName(LogLevel_name, int32(x))
}

func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d3ae338d2e7a3df5, []int{0}
}

type Config struct {
	Server               *Server  `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Logging              *Logging `protobuf:"bytes,2,opt,name=logging,proto3" json:"logging,omitempty"`
	Apis                 []*Api   `protobuf:"bytes,3,rep,name=apis,proto3" json:"apis,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3ae338d2e7a3df5, []int{0}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetServer() *Server {
	if m != nil {
		return m.Server
	}
	return nil
}

func (m *Config) GetLogging() *Logging {
	if m != nil {
		return m.Logging
	}
	return nil
}

func (m *Config) GetApis() []*Api {
	if m != nil {
		return m.Apis
	}
	return nil
}

type Server struct {
	ListenAddr           string   `protobuf:"bytes,1,opt,name=listen_addr,json=listenAddr,proto3" json:"listen_addr,omitempty"`
	Hosts                []*Host  `protobuf:"bytes,2,rep,name=hosts,proto3" json:"hosts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Server) Reset()         { *m = Server{} }
func (m *Server) String() string { return proto.CompactTextString(m) }
func (*Server) ProtoMessage()    {}
func (*Server) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3ae338d2e7a3df5, []int{1}
}

func (m *Server) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Server.Unmarshal(m, b)
}
func (m *Server) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Server.Marshal(b, m, deterministic)
}
func (m *Server) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Server.Merge(m, src)
}
func (m *Server) XXX_Size() int {
	return xxx_messageInfo_Server.Size(m)
}
func (m *Server) XXX_DiscardUnknown() {
	xxx_messageInfo_Server.DiscardUnknown(m)
}

var xxx_messageInfo_Server proto.InternalMessageInfo

func (m *Server) GetListenAddr() string {
	if m != nil {
		return m.ListenAddr
	}
	return ""
}

func (m *Server) GetHosts() []*Host {
	if m != nil {
		return m.Hosts
	}
	return nil
}

type Host struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	KeyPem               string   `protobuf:"bytes,2,opt,name=key_pem,json=keyPem,proto3" json:"key_pem,omitempty"`
	CertPem              string   `protobuf:"bytes,3,opt,name=cert_pem,json=certPem,proto3" json:"cert_pem,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Host) Reset()         { *m = Host{} }
func (m *Host) String() string { return proto.CompactTextString(m) }
func (*Host) ProtoMessage()    {}
func (*Host) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3ae338d2e7a3df5, []int{2}
}

func (m *Host) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Host.Unmarshal(m, b)
}
func (m *Host) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Host.Marshal(b, m, deterministic)
}
func (m *Host) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Host.Merge(m, src)
}
func (m *Host) XXX_Size() int {
	return xxx_messageInfo_Host.Size(m)
}
func (m *Host) XXX_DiscardUnknown() {
	xxx_messageInfo_Host.DiscardUnknown(m)
}

var xxx_messageInfo_Host proto.InternalMessageInfo

func (m *Host) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Host) GetKeyPem() string {
	if m != nil {
		return m.KeyPem
	}
	return ""
}

func (m *Host) GetCertPem() string {
	if m != nil {
		return m.CertPem
	}
	return ""
}

type Logging struct {
	Level                LogLevel `protobuf:"varint,1,opt,name=level,proto3,enum=wgpb.LogLevel" json:"level,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Logging) Reset()         { *m = Logging{} }
func (m *Logging) String() string { return proto.CompactTextString(m) }
func (*Logging) ProtoMessage()    {}
func (*Logging) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3ae338d2e7a3df5, []int{3}
}

func (m *Logging) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Logging.Unmarshal(m, b)
}
func (m *Logging) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Logging.Marshal(b, m, deterministic)
}
func (m *Logging) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Logging.Merge(m, src)
}
func (m *Logging) XXX_Size() int {
	return xxx_messageInfo_Logging.Size(m)
}
func (m *Logging) XXX_DiscardUnknown() {
	xxx_messageInfo_Logging.DiscardUnknown(m)
}

var xxx_messageInfo_Logging proto.InternalMessageInfo

func (m *Logging) GetLevel() LogLevel {
	if m != nil {
		return m.Level
	}
	return LogLevel_DEBUG
}

type Api struct {
	Name                  string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	EngineConfiguration   *EngineConfiguration `protobuf:"bytes,2,opt,name=engine_configuration,json=engineConfiguration,proto3" json:"engine_configuration,omitempty"`
	EnableSingleFlight    bool                 `protobuf:"varint,3,opt,name=enable_single_flight,json=enableSingleFlight,proto3" json:"enable_single_flight,omitempty"`
	EnableGraphqlEndpoint bool                 `protobuf:"varint,4,opt,name=enable_graphql_endpoint,json=enableGraphqlEndpoint,proto3" json:"enable_graphql_endpoint,omitempty"`
	Operations            []*Operation         `protobuf:"bytes,5,rep,name=operations,proto3" json:"operations,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}             `json:"-"`
	XXX_unrecognized      []byte               `json:"-"`
	XXX_sizecache         int32                `json:"-"`
}

func (m *Api) Reset()         { *m = Api{} }
func (m *Api) String() string { return proto.CompactTextString(m) }
func (*Api) ProtoMessage()    {}
func (*Api) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3ae338d2e7a3df5, []int{4}
}

func (m *Api) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Api.Unmarshal(m, b)
}
func (m *Api) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Api.Marshal(b, m, deterministic)
}
func (m *Api) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Api.Merge(m, src)
}
func (m *Api) XXX_Size() int {
	return xxx_messageInfo_Api.Size(m)
}
func (m *Api) XXX_DiscardUnknown() {
	xxx_messageInfo_Api.DiscardUnknown(m)
}

var xxx_messageInfo_Api proto.InternalMessageInfo

func (m *Api) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Api) GetEngineConfiguration() *EngineConfiguration {
	if m != nil {
		return m.EngineConfiguration
	}
	return nil
}

func (m *Api) GetEnableSingleFlight() bool {
	if m != nil {
		return m.EnableSingleFlight
	}
	return false
}

func (m *Api) GetEnableGraphqlEndpoint() bool {
	if m != nil {
		return m.EnableGraphqlEndpoint
	}
	return false
}

func (m *Api) GetOperations() []*Operation {
	if m != nil {
		return m.Operations
	}
	return nil
}

type Operation struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Operation) Reset()         { *m = Operation{} }
func (m *Operation) String() string { return proto.CompactTextString(m) }
func (*Operation) ProtoMessage()    {}
func (*Operation) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3ae338d2e7a3df5, []int{5}
}

func (m *Operation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Operation.Unmarshal(m, b)
}
func (m *Operation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Operation.Marshal(b, m, deterministic)
}
func (m *Operation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Operation.Merge(m, src)
}
func (m *Operation) XXX_Size() int {
	return xxx_messageInfo_Operation.Size(m)
}
func (m *Operation) XXX_DiscardUnknown() {
	xxx_messageInfo_Operation.DiscardUnknown(m)
}

var xxx_messageInfo_Operation proto.InternalMessageInfo

func (m *Operation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Operation) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type EngineConfiguration struct {
	DefaultFlushInterval int64    `protobuf:"varint,1,opt,name=default_flush_interval,json=defaultFlushInterval,proto3" json:"default_flush_interval,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EngineConfiguration) Reset()         { *m = EngineConfiguration{} }
func (m *EngineConfiguration) String() string { return proto.CompactTextString(m) }
func (*EngineConfiguration) ProtoMessage()    {}
func (*EngineConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3ae338d2e7a3df5, []int{6}
}

func (m *EngineConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EngineConfiguration.Unmarshal(m, b)
}
func (m *EngineConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EngineConfiguration.Marshal(b, m, deterministic)
}
func (m *EngineConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EngineConfiguration.Merge(m, src)
}
func (m *EngineConfiguration) XXX_Size() int {
	return xxx_messageInfo_EngineConfiguration.Size(m)
}
func (m *EngineConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_EngineConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_EngineConfiguration proto.InternalMessageInfo

func (m *EngineConfiguration) GetDefaultFlushInterval() int64 {
	if m != nil {
		return m.DefaultFlushInterval
	}
	return 0
}

func init() {
	proto.RegisterEnum("wgpb.LogLevel", LogLevel_name, LogLevel_value)
	proto.RegisterType((*Config)(nil), "wgpb.Config")
	proto.RegisterType((*Server)(nil), "wgpb.Server")
	proto.RegisterType((*Host)(nil), "wgpb.Host")
	proto.RegisterType((*Logging)(nil), "wgpb.Logging")
	proto.RegisterType((*Api)(nil), "wgpb.Api")
	proto.RegisterType((*Operation)(nil), "wgpb.Operation")
	proto.RegisterType((*EngineConfiguration)(nil), "wgpb.EngineConfiguration")
}

func init() { proto.RegisterFile("wundernode_config.proto", fileDescriptor_d3ae338d2e7a3df5) }

var fileDescriptor_d3ae338d2e7a3df5 = []byte{
	// 525 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x93, 0xc1, 0x6f, 0xda, 0x30,
	0x14, 0xc6, 0x07, 0x09, 0x09, 0x3c, 0xb6, 0x2e, 0x72, 0xbb, 0x91, 0x4e, 0x9a, 0x8a, 0xa2, 0x4a,
	0xab, 0x76, 0x80, 0x89, 0x4d, 0x93, 0x76, 0x4c, 0x19, 0x30, 0x54, 0x06, 0xc8, 0xdd, 0x34, 0x69,
	0x97, 0x28, 0x90, 0x47, 0xb0, 0x9a, 0xd8, 0x59, 0x62, 0xa8, 0x7a, 0xdd, 0x5f, 0x3e, 0xc5, 0x0e,
	0x55, 0xa5, 0x71, 0xb3, 0xbf, 0xdf, 0xe7, 0xcf, 0x7e, 0xef, 0xc9, 0xd0, 0xb9, 0xdf, 0xf1, 0x08,
	0x73, 0x2e, 0x22, 0x0c, 0xd6, 0x82, 0x6f, 0x58, 0xdc, 0xcb, 0x72, 0x21, 0x05, 0x31, 0xef, 0xe3,
	0x6c, 0xf5, 0xe6, 0x22, 0x16, 0x22, 0x4e, 0xb0, 0xaf, 0xb4, 0xd5, 0x6e, 0xd3, 0x97, 0x2c, 0xc5,
	0x42, 0x86, 0x69, 0xa6, 0x6d, 0xde, 0x1e, 0xac, 0xa1, 0x3a, 0x46, 0x2e, 0xc1, 0x2a, 0x30, 0xdf,
	0x63, 0xee, 0xd6, 0xba, 0xb5, 0xab, 0xf6, 0xe0, 0x79, 0xaf, 0x4c, 0xe8, 0xdd, 0x2a, 0x8d, 0x56,
	0x8c, 0xbc, 0x03, 0x3b, 0x11, 0x71, 0xcc, 0x78, 0xec, 0xd6, 0x95, 0xed, 0x85, 0xb6, 0xcd, 0xb4,
	0x48, 0x0f, 0x94, 0xbc, 0x05, 0x33, 0xcc, 0x58, 0xe1, 0x1a, 0x5d, 0xe3, 0xaa, 0x3d, 0x68, 0x69,
	0x97, 0x9f, 0x31, 0xaa, 0x64, 0xef, 0x06, 0x2c, 0x9d, 0x4c, 0x2e, 0xa0, 0x9d, 0xb0, 0x42, 0x22,
	0x0f, 0xc2, 0x28, 0xd2, 0x97, 0xb7, 0x28, 0x68, 0xc9, 0x8f, 0xa2, 0x9c, 0x74, 0xa1, 0xb1, 0x15,
	0x85, 0x2c, 0xdc, 0xba, 0x8a, 0x02, 0x1d, 0xf5, 0x4d, 0x14, 0x92, 0x6a, 0xe0, 0xcd, 0xc1, 0x2c,
	0xb7, 0x84, 0x80, 0xc9, 0xc3, 0x14, 0xab, 0x0c, 0xb5, 0x26, 0x1d, 0xb0, 0xef, 0xf0, 0x21, 0xc8,
	0x30, 0x55, 0x0f, 0x6e, 0x51, 0xeb, 0x0e, 0x1f, 0x96, 0x98, 0x92, 0x73, 0x68, 0xae, 0x31, 0x97,
	0x8a, 0x18, 0x8a, 0xd8, 0xe5, 0x7e, 0x89, 0xa9, 0xd7, 0x07, 0xbb, 0xaa, 0x87, 0x5c, 0x42, 0x23,
	0xc1, 0x3d, 0x26, 0x2a, 0xf3, 0x64, 0x70, 0xf2, 0x58, 0xed, 0xac, 0x54, 0xa9, 0x86, 0xde, 0xdf,
	0x3a, 0x18, 0x7e, 0xc6, 0x8e, 0x3e, 0x60, 0x06, 0x67, 0xc8, 0x63, 0xc6, 0x0f, 0xf3, 0xd9, 0xe5,
	0xa1, 0x64, 0x82, 0x57, 0xed, 0x3b, 0xd7, 0x81, 0x23, 0xe5, 0x18, 0x3e, 0x35, 0xd0, 0x53, 0xfc,
	0x5f, 0x24, 0x1f, 0xca, 0xb4, 0x70, 0x95, 0x60, 0x50, 0x30, 0x1e, 0x27, 0x18, 0x6c, 0x12, 0x16,
	0x6f, 0xa5, 0xaa, 0xa0, 0x49, 0x89, 0x66, 0xb7, 0x0a, 0x8d, 0x15, 0x21, 0x9f, 0xa1, 0x53, 0x9d,
	0x88, 0xf3, 0x30, 0xdb, 0xfe, 0x49, 0x02, 0xe4, 0x51, 0x26, 0x18, 0x97, 0xae, 0xa9, 0x0e, 0xbd,
	0xd2, 0x78, 0xa2, 0xe9, 0xa8, 0x82, 0xa4, 0x0f, 0x20, 0x32, 0xd4, 0xd7, 0x16, 0x6e, 0x43, 0xf5,
	0xfe, 0xa5, 0x7e, 0xed, 0xe2, 0xa0, 0xd3, 0x27, 0x16, 0xef, 0x0b, 0xb4, 0x1e, 0xc1, 0xd1, 0x4e,
	0xb8, 0x60, 0xaf, 0x05, 0x97, 0xc8, 0x65, 0x35, 0x8a, 0xc3, 0xd6, 0xbb, 0x81, 0xd3, 0x23, 0x1d,
	0x20, 0x9f, 0xe0, 0x75, 0x84, 0x9b, 0x70, 0x97, 0xc8, 0x60, 0x93, 0xec, 0x8a, 0x6d, 0xc0, 0xb8,
	0xc4, 0x7c, 0x1f, 0xea, 0x69, 0x18, 0xf4, 0xac, 0xa2, 0xe3, 0x12, 0x4e, 0x2b, 0xf6, 0xfe, 0x3b,
	0x34, 0x0f, 0xf3, 0x21, 0x2d, 0x68, 0x7c, 0x1d, 0x5d, 0xff, 0x9c, 0x38, 0xcf, 0x48, 0x13, 0xcc,
	0xe9, 0x7c, 0xbc, 0x70, 0x6a, 0xa5, 0x38, 0xa2, 0x74, 0x41, 0x9d, 0x3a, 0x69, 0x83, 0xfd, 0xcb,
	0xa7, 0xf3, 0xe9, 0x7c, 0xe2, 0x18, 0xa5, 0xbe, 0xf4, 0xe7, 0xd3, 0xa1, 0x63, 0x96, 0xcb, 0xb1,
	0xff, 0xc3, 0x9f, 0x39, 0x8d, 0x6b, 0xeb, 0xb7, 0xfa, 0x4a, 0x2b, 0x4b, 0x7d, 0x98, 0x8f, 0xff,
	0x02, 0x00, 0x00, 0xff, 0xff, 0xd1, 0x62, 0xfc, 0x92, 0x72, 0x03, 0x00, 0x00,
}
