name: publish-npm
on:
  push:
    tags:
      - '*'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@wundergraph'
      - run: yarn
        working-directory: ts
      - run: yarn setVersion
        working-directory: ts
      - run: yarn publish --access public
        working-directory: ts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}